export enum PersonSource {
  SIGNUP_SCREEN_PEOPLE_PLATFORM = 'SIGNUP_SCREEN_PEOPLE_PLATFORM',
  SIGNUP_SCREEN_COMPANY_PLATFORM = 'SIGNUP_SCREEN_COMPANY_PLATFORM',
  ADD_PERSON_SCREEN = 'ADD_PERSON_SCREEN',
  ADD_PERSON_SHARED_DATABASE_SCREEN = 'ADD_PERSON_SHARED_DATABASE_SCREEN',
  ADD_JOB_APPLICATION_PUBLIC_SCREEN = 'ADD_JOB_APPLICATION_PUBLIC_SCREEN',
  ADD_JOB_APPLICATION_PRIVATE_SCREEN = 'ADD_JOB_APPLICATION_PRIVATE_SCREEN',
}
