export const countries = [
  { label: "Afeganistão", value: "Afeganistão" },
  { label: "África do Sul", value: "África do Sul" },
  { label: "Albânia", value: "Albânia" },
  { label: "Alemanha", value: "Alemanha" },
  { label: "Andorra", value: "Andorra" },
  { label: "Angola", value: "Angola" },
  { label: "Anguilla", value: "Anguilla" },
  { label: "Antártida", value: "Antártida" },
  { label: "Antígua e Barbuda", value: "Antígua e Barbuda" },
  { label: "Arábia Saudita", value: "Arábia Saudita" },
  { label: "Argélia", value: "Argélia" },
  { label: "Argentina", value: "Argentina" },
  { label: "Armênia", value: "Armênia" },
  { label: "Aruba", value: "Aruba" },
  { label: "Austrália", value: "Austrália" },
  { label: "Áustria", value: "Áustria" },
  { label: "Azerbaijão", value: "Azerbaijão" },
  { label: "Bahamas", value: "Bahamas" },
  { label: "Bahrein", value: "Bahrein" },
  { label: "Bangladesh", value: "Bangladesh" },
  { label: "Barbados", value: "Barbados" },
  { label: "Belarus", value: "Belarus" },
  { label: "Bélgica", value: "Bélgica" },
  { label: "Belize", value: "Belize" },
  { label: "Benin", value: "Benin" },
  { label: "Bermudas", value: "Bermudas" },
  { label: "Bolívia", value: "Bolívia" },
  { label: "Bósnia-Herzegóvina", value: "Bósnia-Herzegóvina" },
  { label: "Botsuana", value: "Botsuana" },
  { label: "Brasil", value: "Brasil" },
  { label: "Brunei", value: "Brunei" },
  { label: "Bulgária", value: "Bulgária" },
  { label: "Burkina Fasso", value: "Burkina Fasso" },
  { label: "Burundi", value: "Burundi" },
  { label: "Butão", value: "Butão" },
  { label: "Cabo Verde", value: "Cabo Verde" },
  { label: "Camarões", value: "Camarões" },
  { label: "Camboja", value: "Camboja" },
  { label: "Canadá", value: "Canadá" },
  { label: "Canárias", value: "Canárias" },
  { label: "Cazaquistão", value: "Cazaquistão" },
  { label: "Ceuta e Melilla", value: "Ceuta e Melilla" },
  { label: "Chade", value: "Chade" },
  { label: "Chile", value: "Chile" },
  { label: "China", value: "China" },
  { label: "Chipre", value: "Chipre" },
  { label: "Cingapura", value: "Cingapura" },
  { label: "Colômbia", value: "Colômbia" },
  { label: "Comores", value: "Comores" },
  { label: "Congo", value: "Congo" },
  { label: "Coréia do Norte", value: "Coréia do Norte" },
  { label: "Coréia do Sul", value: "Coréia do Sul" },
  { label: "Costa do Marfim", value: "Costa do Marfim" },
  { label: "Costa Rica", value: "Costa Rica" },
  { label: "Croácia", value: "Croácia" },
  { label: "Cuba", value: "Cuba" },
  { label: "Curaçao", value: "Curaçao" },
  { label: "Diego Garcia", value: "Diego Garcia" },
  { label: "Dinamarca", value: "Dinamarca" },
  { label: "Djibuti", value: "Djibuti" },
  { label: "Dominica", value: "Dominica" },
  { label: "Egito", value: "Egito" },
  { label: "El Salvador", value: "El Salvador" },
  { label: "Emirados Árabes Unidos", value: "Emirados Árabes Unidos" },
  { label: "Equador", value: "Equador" },
  { label: "Eritréia", value: "Eritréia" },
  { label: "Eslováquia", value: "Eslováquia" },
  { label: "Eslovênia", value: "Eslovênia" },
  { label: "Espanha", value: "Espanha" },
  { label: "Estados Unidos", value: "Estados Unidos" },
  { label: "Estônia", value: "Estônia" },
  { label: "Etiópia", value: "Etiópia" },
  { label: "Fiji", value: "Fiji" },
  { label: "Filipinas", value: "Filipinas" },
  { label: "Finlândia", value: "Finlândia" },
  { label: "França", value: "França" },
  { label: "Gabão", value: "Gabão" },
  { label: "Gâmbia", value: "Gâmbia" },
  { label: "Gana", value: "Gana" },
  { label: "Geórgia", value: "Geórgia" },
  { label: "Gibraltar", value: "Gibraltar" },
  {
    label: "Grã-Bretanha (Reino Unido, UK)",
    value: "Grã-Bretanha (Reino Unido, UK)",
  },
  { label: "Granada", value: "Granada" },
  { label: "Grécia", value: "Grécia" },
  { label: "Groelândia", value: "Groelândia" },
  { label: "Guadalupe", value: "Guadalupe" },
  {
    label: "Guam (Território dos Estados Unidos)",
    value: "Guam (Território dos Estados Unidos)",
  },
  { label: "Guatemala", value: "Guatemala" },
  { label: "Guernsey", value: "Guernsey" },
  { label: "Guiana", value: "Guiana" },
  { label: "Guiana Francesa", value: "Guiana Francesa" },
  { label: "Guiné", value: "Guiné" },
  { label: "Guiné Equatorial", value: "Guiné Equatorial" },
  { label: "Guiné-Bissau", value: "Guiné-Bissau" },
  { label: "Haiti", value: "Haiti" },
  { label: "Holanda", value: "Holanda" },
  { label: "Honduras", value: "Honduras" },
  { label: "Hong Kong", value: "Hong Kong" },
  { label: "Hungria", value: "Hungria" },
  { label: "Iêmen", value: "Iêmen" },
  { label: "Ilha Bouvet", value: "Ilha Bouvet" },
  { label: "Ilha de Ascensão", value: "Ilha de Ascensão" },
  { label: "Ilha de Clipperton", value: "Ilha de Clipperton" },
  { label: "Ilha de Man", value: "Ilha de Man" },
  { label: "Ilha Natal", value: "Ilha Natal" },
  { label: "Ilha Pitcairn", value: "Ilha Pitcairn" },
  { label: "Ilha Reunião", value: "Ilha Reunião" },
  { label: "Ilhas Aland", value: "Ilhas Aland" },
  { label: "Ilhas Cayman", value: "Ilhas Cayman" },
  { label: "Ilhas Cocos", value: "Ilhas Cocos" },
  { label: "Ilhas Cook", value: "Ilhas Cook" },
  { label: "Ilhas Faroes", value: "Ilhas Faroes" },
  {
    label: "Ilhas Geórgia do Sul e Sandwich do Sul",
    value: "Ilhas Geórgia do Sul e Sandwich do Sul",
  },
  {
    label: "Ilhas Heard e McDonald (Território da Austrália)",
    value: "Ilhas Heard e McDonald (Território da Austrália)",
  },
  { label: "Ilhas Malvinas", value: "Ilhas Malvinas" },
  { label: "Ilhas Marianas do Norte", value: "Ilhas Marianas do Norte" },
  { label: "Ilhas Marshall", value: "Ilhas Marshall" },
  {
    label: "Ilhas Menores dos Estados Unidos",
    value: "Ilhas Menores dos Estados Unidos",
  },
  { label: "Ilhas Norfolk", value: "Ilhas Norfolk" },
  { label: "Ilhas Salomão", value: "Ilhas Salomão" },
  { label: "Ilhas Seychelles", value: "Ilhas Seychelles" },
  { label: "Ilhas Tokelau", value: "Ilhas Tokelau" },
  { label: "Ilhas Turks e Caicos", value: "Ilhas Turks e Caicos" },
  {
    label: "Ilhas Virgens (Estados Unidos)",
    value: "Ilhas Virgens (Estados Unidos)",
  },
  { label: "Ilhas Virgens (Inglaterra)", value: "Ilhas Virgens (Inglaterra)" },
  { label: "Índia", value: "Índia" },
  { label: "Indonésia", value: "Indonésia" },
  { label: "Irã", value: "Irã" },
  { label: "Iraque", value: "Iraque" },
  { label: "Irlanda", value: "Irlanda" },
  { label: "Islândia", value: "Islândia" },
  { label: "Israel", value: "Israel" },
  { label: "Itália", value: "Itália" },
  { label: "Jamaica", value: "Jamaica" },
  { label: "Japão", value: "Japão" },
  { label: "Jersey", value: "Jersey" },
  { label: "Jordânia", value: "Jordânia" },
  { label: "Kiribati", value: "Kiribati" },
  { label: "Kosovo", value: "Kosovo" },
  { label: "Kuait", value: "Kuait" },
  { label: "Laos", value: "Laos" },
  { label: "Lesoto", value: "Lesoto" },
  { label: "Letônia", value: "Letônia" },
  { label: "Líbano", value: "Líbano" },
  { label: "Libéria", value: "Libéria" },
  { label: "Líbia", value: "Líbia" },
  { label: "Liechtenstein", value: "Liechtenstein" },
  { label: "Lituânia", value: "Lituânia" },
  { label: "Luxemburgo", value: "Luxemburgo" },
  { label: "Macau", value: "Macau" },
  {
    label: "Macedônia (República Yugoslava)",
    value: "Macedônia (República Yugoslava)",
  },
  { label: "Madagascar", value: "Madagascar" },
  { label: "Malásia", value: "Malásia" },
  { label: "Malaui", value: "Malaui" },
  { label: "Maldivas", value: "Maldivas" },
  { label: "Mali", value: "Mali" },
  { label: "Malta", value: "Malta" },
  { label: "Marrocos", value: "Marrocos" },
  { label: "Martinica", value: "Martinica" },
  { label: "Maurício", value: "Maurício" },
  { label: "Mauritânia", value: "Mauritânia" },
  { label: "Mayotte", value: "Mayotte" },
  { label: "México", value: "México" },
  { label: "Micronésia", value: "Micronésia" },
  { label: "Moçambique", value: "Moçambique" },
  { label: "Moldova", value: "Moldova" },
  { label: "Mônaco", value: "Mônaco" },
  { label: "Mongólia", value: "Mongólia" },
  { label: "Montenegro", value: "Montenegro" },
  { label: "Montserrat", value: "Montserrat" },
  { label: "Myanma", value: "Myanma" },
  { label: "Namíbia", value: "Namíbia" },
  { label: "Nauru", value: "Nauru" },
  { label: "Nepal", value: "Nepal" },
  { label: "Nicarágua", value: "Nicarágua" },
  { label: "Níger", value: "Níger" },
  { label: "Nigéria", value: "Nigéria" },
  { label: "Niue", value: "Niue" },
  { label: "Noruega", value: "Noruega" },
  { label: "Nova Caledônia", value: "Nova Caledônia" },
  { label: "Nova Zelândia", value: "Nova Zelândia" },
  { label: "Omã", value: "Omã" },
  { label: "Países Baixos Caribenhos", value: "Países Baixos Caribenhos" },
  { label: "Palau", value: "Palau" },
  { label: "Palestina", value: "Palestina" },
  { label: "Panamá", value: "Panamá" },
  { label: "Papua-Nova Guiné", value: "Papua-Nova Guiné" },
  { label: "Paquistão", value: "Paquistão" },
  { label: "Paraguai", value: "Paraguai" },
  { label: "Peru", value: "Peru" },
  { label: "Polinésia Francesa", value: "Polinésia Francesa" },
  { label: "Polônia", value: "Polônia" },
  { label: "Porto Rico", value: "Porto Rico" },
  { label: "Portugal", value: "Portugal" },
  { label: "Qatar", value: "Qatar" },
  { label: "Quênia", value: "Quênia" },
  { label: "Quirguistão", value: "Quirguistão" },
  { label: "República Centro-Africana", value: "República Centro-Africana" },
  {
    label: "República Democrática do Congo",
    value: "República Democrática do Congo",
  },
  { label: "República Dominicana", value: "República Dominicana" },
  { label: "República Tcheca", value: "República Tcheca" },
  { label: "Romênia", value: "Romênia" },
  { label: "Ruanda", value: "Ruanda" },
  {
    label: "Rússia (antiga URSS) - Federação Russa",
    value: "Rússia (antiga URSS) - Federação Russa",
  },
  { label: "Saara Ocidental", value: "Saara Ocidental" },
  { label: "Saint-Pierre e Miquelon", value: "Saint-Pierre e Miquelon" },
  { label: "Samoa Americana", value: "Samoa Americana" },
  { label: "Samoa Ocidental", value: "Samoa Ocidental" },
  { label: "San Marino", value: "San Marino" },
  { label: "Santa Helena", value: "Santa Helena" },
  { label: "Santa Lúcia", value: "Santa Lúcia" },
  { label: "São Bartolomeu", value: "São Bartolomeu" },
  { label: "São Cristóvão e Névis", value: "São Cristóvão e Névis" },
  { label: "São Martim", value: "São Martim" },
  { label: "São Martinho", value: "São Martinho" },
  { label: "São Tomé e Príncipe", value: "São Tomé e Príncipe" },
  { label: "São Vicente e Granadinas", value: "São Vicente e Granadinas" },
  { label: "Senegal", value: "Senegal" },
  { label: "Serra Leoa", value: "Serra Leoa" },
  { label: "Sérvia", value: "Sérvia" },
  { label: "Síria", value: "Síria" },
  { label: "Somália", value: "Somália" },
  { label: "Sri Lanka", value: "Sri Lanka" },
  { label: "Suazilândia", value: "Suazilândia" },
  { label: "Sudão", value: "Sudão" },
  { label: "Sudão do Sul", value: "Sudão do Sul" },
  { label: "Suécia", value: "Suécia" },
  { label: "Suíça", value: "Suíça" },
  { label: "Suriname", value: "Suriname" },
  { label: "Svalbard", value: "Svalbard" },
  { label: "Tadjiquistão", value: "Tadjiquistão" },
  { label: "Tailândia", value: "Tailândia" },
  { label: "Taiwan", value: "Taiwan" },
  { label: "Tanzânia", value: "Tanzânia" },
  {
    label: "Território Britânico do Oceano índico",
    value: "Território Britânico do Oceano índico",
  },
  {
    label: "Territórios do Sul da França",
    value: "Territórios do Sul da França",
  },
  { label: "Timor-Leste", value: "Timor-Leste" },
  { label: "Togo", value: "Togo" },
  { label: "Tonga", value: "Tonga" },
  { label: "Trinidad e Tobago", value: "Trinidad e Tobago" },
  { label: "Tristão da Cunha", value: "Tristão da Cunha" },
  { label: "Tunísia", value: "Tunísia" },
  { label: "Turcomenistão", value: "Turcomenistão" },
  { label: "Turquia", value: "Turquia" },
  { label: "Tuvalu", value: "Tuvalu" },
  { label: "Ucrânia", value: "Ucrânia" },
  { label: "Uganda", value: "Uganda" },
  { label: "Uruguai", value: "Uruguai" },
  { label: "Uzbequistão", value: "Uzbequistão" },
  { label: "Vanuatu", value: "Vanuatu" },
  { label: "Vaticano", value: "Vaticano" },
  { label: "Venezuela", value: "Venezuela" },
  { label: "Vietnã", value: "Vietnã" },
  { label: "Wallis e Futuna", value: "Wallis e Futuna" },
  { label: "Zâmbia", value: "Zâmbia" },
  { label: "Zimbábue", value: "Zimbábue" },
];